### ISSUE TITLE
netstandard2.0

### ISSUE THREAD

**Issue by svrooij** [kenswan/AutomationIoC#7]
Is there a specific reason why you're targeting .net6? I would really like to use the dependency injection for my new PowerShell module, but I would also like to still support the old Windows PowerShell.

I was thinking about maybe dual targeting if that would be necessary.

**Comment by kenswan** [comment]
@svrooij thank you for the input. That's a great suggestion. I ran some quick tests locally to check any regression and there's some specific runtime/language features that are not available in `netstandard2.0` and breaks the current build (ex. `using declarations`, `not pattern`, xunit.runner.visualstudio package dependency, `file-scoped namespace`, etc.). Though targeting `netstandard2.0` is not fully feasible with the current project right now, let me know if there are any other suggestions that may help ease the support for legacy modules.

**Comment by kenswan** [comment]
Added support for netstandard2.1
